POST http://localhost:8080/v1/feeds
Authorization: ApiKey 425a7237fd6c36a76b2e7400a370e67608f619118a34f9fa9b3c79314fbe21fc

{
  "name": "Something cool",
  "url": "http://example.com/feed-kiquetal-something.xml"
}

